@startuml
left to right direction

class TollLaneComputer {
    {method} +checkIn(vehicleType: VehicleType)
    {method} +printTicket(ticket: Ticket)
    {method} +raiseBarrier()
    {method} +lowerBarrier()
    {method} +processPayment(creditCardInfo: CreditCard)
    {method} +readCreditCard()
}


' class StationServer {
'     {method} +processCreditCardPayment()
' }

' class EnterpriseServer { 
'     {method} +processPayment()
' }

class TicketPrinter { 
    {method} +printTicket(ticket: Ticket)
}

class Barrier {
    {method} +raiseBarrier()
    {method} +lowerBarrier()
}

class CreditCardReader {
    {method} +readCreditCard()
}
 
interface TicketPrinterToTollLaneComputer {
    {method} +printTicket()
}

interface BarrierToTollLaneComputer {
    {method} +raiseBarrier()
    {method} +lowerBarrier()
}

interface StationServerToTollLaneComputer {
    {method} +processPayment(creditCardInfo: CreditCard)
}

interface CreditCardReaderToTollLaneComputer {
    {method} +readCreditCard()
}

TicketPrinter .l.|> TicketPrinterToTollLaneComputer
Barrier .r.|> BarrierToTollLaneComputer
CreditCardReader .l.|> CreditCardReaderToTollLaneComputer
TollLaneComputer --> "1" CreditCardReaderToTollLaneComputer
TollLaneComputer --> "1" BarrierToTollLaneComputer
TollLaneComputer --> "1" TicketPrinterToTollLaneComputer
TollLaneComputer  --> "1" StationServerToTollLaneComputer

@enduml 